#!/bin/bash

echo "🚀 FINAL UPLOAD - Complete Fresh Deployment"
echo ""
echo "IMPORTANT: Use FileZilla for this!"
echo ""
echo "📋 STEPS:"
echo ""
echo "1. Open FileZilla"
echo "2. Connect: 197.242.150.197"
echo "3. User: admin@thynkxpro-dpl.co.za"
echo "4. Pass: Wesley123@123"
echo ""
echo "5. On SERVER (right side): Navigate to /"
echo "6. DELETE these folders on server:"
echo "   - _next"
echo "   - All .html files"
echo ""
echo "7. On LOCAL (left side): Go to:"
echo "   /Users/siyandazama/Documents/rental-billing-dashboard/out/"
echo ""
echo "8. SELECT ALL in 'out' folder (Cmd+A)"
echo "9. DRAG to server"
echo "10. Choose 'Overwrite' for all"
echo ""
echo "11. Wait for upload to complete (~2-3 minutes)"
echo ""
echo "12. After upload:"
echo "    - Clear browser cache (Cmd+Shift+Delete)"
echo "    - Hard refresh: Cmd+Shift+R"
echo "    - Test: http://thynkxpro-dpl.co.za/login.html"
echo ""
echo "✅ Your tenants will appear after this!"
echo ""
